import { Montserrat } from "next/font/google";
import "./globals.css";

// Import Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Include weights as needed
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body cz-shortcut-listen="true" className="antialiased">
        {children}
      </body>
    </html>
  );
}
